# Fish config managed by stow

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

# Source home-manager session vars if available
if test -f /etc/profile.d/hm-session-vars.fish
    source /etc/profile.d/hm-session-vars.fish
else if test -f $HOME/.config/fish/hm-session-vars.fish
    source $HOME/.config/fish/hm-session-vars.fish
end

# Source handler functions

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases

    # Interactive shell initialisation
    set fish_greeting

    # kitty doesn't clear properly
    alias clear "printf '\033[2J\033[3J\033[1;1H'"
    alias celar "printf '\033[2J\033[3J\033[1;1H'"
    alias claer "printf '\033[2J\033[3J\033[1;1H'"
    alias pamcan pacman
    alias q 'qs -c ii'

    if test "$TERM" != linux
        alias ls 'eza --icons'
    end
    if test "$TERM" = xterm-kitty
        alias ssh 'kitten ssh'
    end

    set -g FLAKE "$HOME/git/dotties/nixos"

    function dev --inherit-variable FLAKE
        if test (count $argv) -eq 0
            nix develop "$FLAKE#default"
        else if string match -qr -- '^(--help|-h|list)$' "$argv[1]"
            echo "Available devshells:"
            nix eval "$FLAKE#devShells.x86_64-linux" --apply 'builtins.attrNames' 2>/dev/null \
                | string match -ra '\w+' \
                | while read -l shell
                echo "    $shell"
            end
            echo ""
            echo "Usage:"
            echo "  dev <name>           Enter a single devshell"
            echo "  dev <name> <name>    Combine multiple devshells"
            echo "  dev all              Everything"
            echo "  dev fullstack        web + rust + go + java + backend"
            echo "  dev data             python + go"
            echo "  dev cloud            devops + go"
        else if test (count $argv) -eq 1
            nix develop "$FLAKE#"$argv[1]
        else
            # Combine multiple devshells dynamically
            set -l shellList (string join ' ' $argv)
            set -l tmpfile (mktemp /tmp/devshell.XXXXXX.nix)
            echo let >$tmpfile
            echo "  flake = builtins.getFlake \"$FLAKE\";" >>$tmpfile
            echo "  pkgs = import flake.inputs.nixpkgs { system = \"x86_64-linux\"; };" >>$tmpfile
            echo "  shells = with flake.devShells.x86_64-linux; [ $shellList ];" >>$tmpfile
            echo "in pkgs.mkShell {" >>$tmpfile
            echo "  inputsFrom = shells;" >>$tmpfile
            echo "  shellHook = \"exec fish\";" >>$tmpfile
            echo "}" >>$tmpfile
            nix develop -f $tmpfile
            rm $tmpfile
        end
    end

    if test "$TERM" != dumb
        starship init fish | source

    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION no-rc
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/legion/.local/share/fish/home-manager/generated_completions" $post
    end

end
